"""booking management_token and overlap predicate fix

Revision ID: 2d6bb453b440
Revises: 13cb6bc1824e
Create Date: 2026-06-18 21:08:18.345318

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.db.constraints import ADD_OVERLAP_CONSTRAINT_SQL, DROP_OVERLAP_CONSTRAINT_SQL

# revision identifiers, used by Alembic.
revision: str = "2d6bb453b440"
down_revision: str | None = "13cb6bc1824e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("management_token", sa.String(length=64), nullable=True))
    op.create_index(
        op.f("ix_bookings_management_token"), "bookings", ["management_token"], unique=True
    )
    # ### end Alembic commands ###

    # Пересоздаём EXCLUDE-ограничение без статуса 'rescheduled' в активном наборе: при переносе
    # старая бронь переходит в 'rescheduled' и должна освобождать слот (ТЗ §4.5 КП).
    op.execute(DROP_OVERLAP_CONSTRAINT_SQL)
    op.execute(ADD_OVERLAP_CONSTRAINT_SQL)


def downgrade() -> None:
    # Возвращаем исходный предикат EXCLUDE-ограничения (со статусом 'rescheduled').
    op.execute(DROP_OVERLAP_CONSTRAINT_SQL)
    op.execute(
        """
        ALTER TABLE bookings ADD CONSTRAINT excl_bookings_host_no_overlap
        EXCLUDE USING gist (
            host_id WITH =,
            tstzrange(start_utc, end_utc, '[)') WITH &&
        )
        WHERE (status IN ('confirmed', 'pending_payment', 'rescheduled'))
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bookings_management_token"), table_name="bookings")
    op.drop_column("bookings", "management_token")
    # ### end Alembic commands ###
